name: fantasy
dependencies:
  - python=3.7
  - numpy
  - pandas
  - pip
  - pip:
    - yahoo_oauth
    - yahoo_fantasy_api
    - python-dotenv
    - XlsxWriter
    - "-e git+https://github.com/tefirman/sportsipy.git#egg=sportsipy"
