name: fantasy
dependencies:
  - python=3.10
  - numpy
  - pandas
  - wget
  - pip
  - pip:
    - yahoo_oauth
    - yahoo_fantasy_api
    - python-dotenv
    - XlsxWriter
    - geopy
    - matplotlib
    - beautifulsoup4
    - Unidecode
    - black
    - lxml
    - scipy
    - pdoc
    - html5lib
