name: fantasy
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pip
  - pip:
    - yahoo_oauth
    - yahoo_fantasy_api
    - python-dotenv
    - XlsxWriter
    - beautifulsoup4
    - Unidecode
    - black
    - "-e git+https://github.com/tefirman/sportsipy.git#egg=sportsipy"
